# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170411_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='username',
            new_name='user',
        ),
    ]
